class sklearn.model_selection.KFold(n_splits=5, *, shuffle=False, random_state=None)

In [15]:
import numpy as np

In [19]:
X = np.array([[1, 2], [3, 4], [1, 2], [3, 4], [5, 6], [7, 8], [9, 0]])
y = np.array([1, 2, 3, 4, 2, 3, 1])

In [20]:
X.shape, y.shape

((7, 2), (7,))

In [21]:
from sklearn.model_selection import KFold

In [23]:
kf = KFold(n_splits=2, shuffle=True)

In [24]:
kf.get_n_splits(X)

2

In [25]:
for first, second in kf.split(X):
  print(first, ' : ', second)

[2 3 4]  :  [0 1 5 6]
[0 1 5 6]  :  [2 3 4]


In [26]:
kf = KFold(n_splits=3, shuffle=True)

In [27]:
for first, second in kf.split(X):
  print(first, ' : ', second)

[1 2 3 6]  :  [0 4 5]
[0 1 4 5 6]  :  [2 3]
[0 2 3 4 5]  :  [1 6]


In [29]:
type(first), type(second)          # 리스트나 넘파이는 마스크를 할 수 있다. 

(numpy.ndarray, numpy.ndarray)

In [32]:
first.shape, second.shape

((5,), (2,))

In [36]:
for first, second in kf.split(X):
  print(first, ' : ', second)
  x_train = X[first]
  print(x_train)
  x_test = X[second]
  print(x_test)

[0 4 5 6]  :  [1 2 3]
[[1 2]
 [5 6]
 [7 8]
 [9 0]]
[[3 4]
 [1 2]
 [3 4]]
[0 1 2 3 5]  :  [4 6]
[[1 2]
 [3 4]
 [1 2]
 [3 4]
 [7 8]]
[[5 6]
 [9 0]]
[1 2 3 4 6]  :  [0 5]
[[3 4]
 [1 2]
 [3 4]
 [5 6]
 [9 0]]
[[1 2]
 [7 8]]
