class sklearn.model_selection.KFold(n_splits=5, *, shuffle=False, random_state=None)

In [1]:
import numpy as np

In [2]:
X = np.array([[1, 2], [3, 4], [1, 2], [3, 4], [5, 6], [7, 8], [9, 0]])
y = np.array([1, 2, 3, 4, 2, 3, 1])

In [3]:
X.shape, y.shape

((7, 2), (7,))

In [4]:
from sklearn.model_selection import KFold

In [16]:
kf = KFold(n_splits=2, shuffle=True)

In [17]:
kf.get_n_splits(X)

2

In [18]:
for first, second in kf.split(X):
  print(first, ' : ', second)

[0 4 6]  :  [1 2 3 5]
[1 2 3 5]  :  [0 4 6]


In [8]:
kf = KFold(n_splits=3, shuffle=True)

In [9]:
for first, second in kf.split(X):
  print(first, ' : ', second)

[0 2 4 6]  :  [1 3 5]
[0 1 2 3 5]  :  [4 6]
[1 3 4 5 6]  :  [0 2]


### 마스킹이란 원하는 조건을 달아서 조건에 맞는 배열요소들만 걸러내는 작업이다.
True/False를 반환하는 조건을 인덱스처럼 집어 넣으면 조건의 True 값을 반환하는 원소들만 뽑아낼 수 있다.

In [10]:
type(first), type(second)          # 리스트나 넘파이는 마스크를 할 수 있다. 

(numpy.ndarray, numpy.ndarray)

In [11]:
first.shape, second.shape

((5,), (2,))

In [12]:
for first, second in kf.split(X):
  print(first, ' : ', second)
  x_train = X[first]
  print(x_train)
  x_test = X[second]
  print(x_test)

[0 1 3 4]  :  [2 5 6]
[[1 2]
 [3 4]
 [3 4]
 [5 6]]
[[1 2]
 [7 8]
 [9 0]]
[0 2 4 5 6]  :  [1 3]
[[1 2]
 [1 2]
 [5 6]
 [7 8]
 [9 0]]
[[3 4]
 [3 4]]
[1 2 3 5 6]  :  [0 4]
[[3 4]
 [1 2]
 [3 4]
 [7 8]
 [9 0]]
[[1 2]
 [5 6]]
