In [ ]:
import numpy as np

In [ ]:
np.__version__         # __는 내장변수를 뜻하는 것임.

'1.19.5'

In [ ]:
# def onhotcylinder(cylinders):
#   if cylinders == 3:
#     cylinder = np.array([1,0,0,0,0])
#   elif cylinders == 4:
#     cylinder = np.array([0,1,0,0,0])
#   elif cylinders == 5:
#     cylinder = np.array([0,0,1,0,0])
#   elif cylinders == 6:
#     cylinder = np.array([0,0,0,1,0])
#   else: # 8
#     cylinder = np.array([0,0,0,0,1]) 
#   return cylinder

In [ ]:
# def onehotorigin(origin):
#   if origin == 1:
#     org = np.array([1,0,0])
#   elif origin == 2:
#     org = np.array([0,1,0])
#   else:
#     org = np.array([0,0,1])
#   return org

In [ ]:
# displacement = 307.9
# horsepower = 130.0
# weight = 3504.0
# accel = 12.0
# cylinders = 8
# origin = 1

# ## if cylinders = 8, origin = 1 ---> onehot encoding
# import numpy as np

# X_continues = np.array([displacement, horsepower, weight, accel])
# # cylinder = np.array([0,0,0,0,1])  # 8
# cylinder = onhotcylinder(cylinders)
# # org = np.array([1,0,0])  # 1
# org = onehotorigin(origin)

In [ ]:
# onhotcylinder(4), onhotcylinder(6)

In [ ]:
# onehotorigin(2), onehotorigin(3)

(array([0, 1, 0]), array([0, 0, 1]))

In [ ]:
# type(X_continues), type(cylinder), type(org)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

numpy.concatenate : numpy 배열들을 하나로 합치는데 이용         api에서 예제를 사용해볼 것   
np.concatenate((a, b), axis=None)

concatenate 미국식 [kɑnkǽtənèit]  영국식 [kɔn-] 1. [타동사] 사슬같이 잇다; 연쇄시키다;

In [ ]:
# result = np.concatenate((X_continues, cylinder, org), axis=None)                    
# result.shape, result

((12,),
 array([3.079e+02, 1.300e+02, 3.504e+03, 1.200e+01, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 1.000e+00, 1.000e+00, 0.000e+00, 0.000e+00]))

e : 승수를 뜻함  +02 는 *100, +03은 *1000, +01은 *10을 뜻함

[307.0, 130.0, 3504.0, 12.0, 0,0,0,0,1,1,0,0 ] 과 같음
행열의 구조로 넣어주어야 함. (1,12)형태로... 그래서 reshape을 쓴다. 

In [ ]:
#  result.reshape(1,12), result.size

result = reshape(-1, result.size) 도 같은 결과를 가져올 수 있다. (소프트코딩 방법) <br> -1은 자기 연산을 뜻함.

In [ ]:
# result

array([3.079e+02, 1.300e+02, 3.504e+03, 1.200e+01, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 1.000e+00, 1.000e+00, 0.000e+00, 0.000e+00])

In [ ]:
# def concana(X_continues, cylinder, org):
#     con = np.concatenate((X_continues, cylinder, org), axis=None)
#     result = con.reshape(1,12)
#     return result

In [ ]:
# result

array([3.079e+02, 1.300e+02, 3.504e+03, 1.200e+01, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 1.000e+00, 1.000e+00, 0.000e+00, 0.000e+00])

# function 이해

In [ ]:
# function은 공통적인 것을 묶는 것 --> 반복적인 작업의 기능화

In [ ]:
21 + 14

In [ ]:
32 + 45

In [ ]:
def sum():
  first = 32
  second = 45
  result = first + second
  return result

In [ ]:
def sum(f,s):      # 함수의 외부에선 순서가 중요하고 내부에서는 이름이 중요하다. 
  first = s
  second = f
  result = first + second
  return result, first, second

In [ ]:
sum(4,5), sum(3,2), sum(21,564)

In [ ]:
r01,r02,r03 = sum(23, 2)
print(r01,r02)

In [ ]:
21 * 32 * 2

In [ ]:
31 * 63 * 41

In [ ]:
def multi(x,y,z):
  result = x * y * z
  return result

In [ ]:
multi(21,32,2), multi(31,63,41)

In [ ]:
# def differenceVars(*var01, **args02)
def diffparam(*var_list, **var_dict):           # 파라미터가 list일 경우 *, dictionary일 경우 **를 쓴다. 요즘 많이 쓰고 있다. 
  print(var_dict)
  result01 = len(var_list)
  return result01

In [ ]:
diffparam(1,2,3, a=2,b=3)

In [ ]:
diffparam(1,2,3,5,6, d=6,a=2,b=3,c=5)